language: ruby
sudo: false

before_install: gem install bundler --no-document

rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.2
  - jruby-19mode

gemfile:
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-5.0.x

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: test/gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-5.0.x
    - rvm: jruby-19mode
      gemfile: test/gemfiles/Gemfile.rails-5.0.x
